name: Skinalyze
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: CalDev.Skinalyze
targets:
  Skinalyze:
    type: application
    platform: iOS
    sources: [Skinalyze]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: CalDev.Skinalyze.Skinalyze
      INFOPLIST_FILE: Skinalyze/Info.plist
schemes:
  Skinalyze:
    build:
      targets:
        Skinalyze: all